### ISSUE TITLE
LMDB allocating whole file

### ISSUE THREAD

**Issue by Nekromancer** [Spreads/Spreads.LMDB#10]
After last nuget update the lmdb database allocated whole file (as declared in MapSize) at start. I was using 1TB MapSize, since there was no problem with that earlier. Now i can't open the environment using new version (disk is too small). Is this planned? Can i set dynamic file size somehow?

**Comment by Nekromancer** [comment]
Yes. I'm not sure if we can set lower MapSize and then resize it on existing database. I couldn't find any solid information on that. So we're using 1TB MapSize, just in case.

Commit size is one culpit. Another is - when an application crashes without disposing environment. I think system is trying to dump virtual memory. But when virtual memory is 1TB it takes like 15 minutes. And system is totally unresponsive during that process. Background services are working fine, but i can't open Task Manager or anything system related

**Comment by buybackoff** [comment]
Are you on Linux? On Win10 system writes only dirty pages, I would have
notices.

Howard Chu explicitly said somewhere that "as large as possible" means free
disk space, so you should set 1 TB if you have so much and realistically
could reach this size.

**Comment by Nekromancer** [comment]
Nope, i'm running it on Windows Server 2016. Every time when an unhandled exceptions slips - whole system goes unresponsive like that for 15-20 minutes. It's really weird, same thing happed using Lightning.NET, so i figured it's LMDB (or simple huge memory mapped file) issue.

Well, we are growing pretty fast and 1TB is realistic in matter of 1-2 years. But now we are operating on 480 GB SSD drive, so we don't have the capacity now (just waiting for it to be needed)

**Comment by buybackoff** [comment]
Then set it to 50-100Gb or something, you could always increase it at any
time unless you are planning for no code updates or restarts after initial
launch :)

Also you could use separate environments when you do not need atomic
transactions between tables.

**Comment by Nekromancer** [comment]
Strange thing - using nuget version `1.0.0-build1809241224` i still encounter this allocation. The only flag i use is `DbEnvironmentFlags.NoMemInit`.

I'm using this db almost only for random reads (lots of them). Write are only synchronous and pretty rare.

**Comment by buybackoff** [comment]
One thing, botstrapper that extracts native lib from resource does not
overwrite existing. Try to remove x64 folder in bin folder. But still I do
not remember pushing the release native lib. Will clean everything and push
again in an hour or so.

File system is NTFS?

**Comment by buybackoff** [comment]
BTW, there is a test that opens 10TB env https://github.com/Spreads/Spreads.LMDB/blob/e1d1c5ed4a51bc9ab57535960bf0713688e4f12d/test/Spreads.LMDB.Tests/LMDBTests.cs#L212

**Comment by buybackoff** [comment]
I have just cleaned all bin/obj folders and republished NuGet. It definetly could open 10 TB env on my Win10 machine.

**Comment by Nekromancer** [comment]
I tried removing x64 folder, no luck here. Yes, my file system is NTFS. After downgrading nuget to '1.0.0-build1809121439' everything works like good

**Comment by buybackoff** [comment]
Very strange, I have this error on a clean console app. All my apps depending on NuGet work just fine. Will fix now.

**Comment by buybackoff** [comment]
Now it works in a clean console app. Creating 2 TB env just uses 8 kb file. Maybe I accidentally compiled native from release branch and that leaked into `lib/out` folder and NuGet.

**Comment by Nekromancer** [comment]
Now it's working great, thanks for quick reaction :)
