### ISSUE TITLE
Some higher level apis

### ISSUE THREAD

**Issue by Nekromancer** [Spreads/Spreads.LMDB#12]
Have you considered some higher level apis in your library? For example - for someone who doesn't care about Span/Memory library could expose enumerators on duplicate entries and so on. Little things that would make using this wrapper a little bit easier and faster (in development time). I could open some PRs on this

**Comment by buybackoff** [comment]
`AsEnumerable` overloads are already there https://github.com/Spreads/Spreads.LMDB/blob/9abf5677fdbf7a459ca514bd3a02d0fef40284bc/src/Spreads.LMDB/Database.cs#L582-L725

Also there are `TryFind/TryFindDup` methods on cursors and DBs that allow searching `LessThan/LessOrEqual/GE/GT` in one go.

PRs are welcome!

**Comment by buybackoff** [comment]
The lib intended to be low-level. I think IEnumerable support + Generics is enough. Please open issues for specific requests if any.
