### ISSUE TITLE
Base class for transaction

### ISSUE THREAD

**Issue by Nekromancer** [Spreads/Spreads.LMDB#14]
Have you considered creating base class for transaction for use with shared functionality?

For example, you can open ReadOnlyCursor on both `Transaction` or `ReadOnlyTransaction`. But i want to create shared code for cursor enumeration. Right now i came up with this:

```csharp
public void Iterate(object transaction)
{
            if (transaction is Transaction tx)
            {
                foreach (var item in db.AsEnumerable(tx, key)
                {
                    // do something with item
                }
            }
            else if (transaction is ReadOnlyTransaction rotx)
            {
                foreach (var item in db.AsEnumerable(rotx, key)
                {
                    // do something with item
                }
            }
            else
            {
                throw new ArgumentException("Not an Transaction object", nameof(transaction));
            }
}
```

It's working, but i find it very ugly. Is there a reason why you didn't use some shared base class? The way i see it - `ReadWriteTransaction` should be inheriting from `ReadOnlyTransaction`

**Comment by Nekromancer** [comment]
Well, that solution seems good enough :)

**Comment by buybackoff** [comment]
Actually this is not usable yet. There are internal checks that txn is read-only.

**Comment by buybackoff** [comment]
I'm reworking internals, maybe txn will be a single class, not even base/parent. In C it is a single struct.

Found that when pooling is off SafeHandle allocates a lot. And reads should become faster.

**Comment by Nekromancer** [comment]
All tests are green now
