### ISSUE TITLE
Nuget package does not contain a Mac runtime

### ISSUE THREAD

**Issue by aliostad** [Spreads/Spreads.LMDB#25]
I have taken a dependency to the package but unfortunately the nuget package does not contain a Mac runtime for `libspreads_lmdb.so`. 

Can you please add support for mac?

**Comment by buybackoff** [comment]
Could you send a PR? I believe you only need to change .so to .dylib in `lib/libspreadsdb/src/libspreadsdb/Makefile` and call `Make`.

**Comment by buybackoff** [comment]
Actually I had it on my TODOs https://github.com/Spreads/Spreads.Native/issues/1

Will do myself later all three native libs I have in Spreads. I'm on Mac Air but using Windows and have to reboot and setup dev tools from scratch.
