### ISSUE TITLE
Stable version are not extracting native libraries

### ISSUE THREAD

**Issue by Nekromancer** [Spreads/Spreads.LMDB#28]
Like in title - newest version isn't extracting native library for me:

![image](https://user-images.githubusercontent.com/3933348/56206273-443adc80-604c-11e9-9471-620e1a5c73c0.png)

Last working version is `1.0.0-build1903282013`.
Is this expected? Should i provide native library myself?

**Comment by buybackoff** [comment]
Native libs now packed with NuGet in runtimes/native folder. On .NET classic framework it failed for me. There should be runtimes folder, move native dll to the same folder as this lib dll.

**Comment by Nekromancer** [comment]
Copying that file worked. Could i ask why did you get rid of bootstrapper?

**Comment by buybackoff** [comment]
Because NuGet is supposed to work well. And on Linux .so must be in the same folder as .NET lib that calls it, otherwise DllImport doesn't work and the only way is to create delegates to native functions.

**Comment by Nekromancer** [comment]
Ok, so that's malfunction of .net classic target framework. I can live with that. Thanks for help
