### ISSUE TITLE
libmdbx

### ISSUE THREAD

**Issue by Nekromancer** [Spreads/Spreads.LMDB#3]
Hey,

First of all - thanks for the great job here. I have been using Lightning.NET in our big project, and allocations made by it were killing our servers constantly. Spreads.LMDB seems to be working much better so far. I will be testing it further.

Have you looked at (and considered) using libmdbx instead of LMDB? It have many improvements over LMDB and project seems to be very active.

Check it out: https://github.com/leo-yuriev/libmdbx

**Comment by buybackoff** [comment]
I know about libmdbx but am neutral about it. You could switch binaries easily, put dll in 'lib/out' folder and run compress.bat, it will be deflated and packed as resource. There is small readme in lib folder how to build/pack native libs.

**Comment by Nekromancer** [comment]
Thanks, i'll try it out

**Comment by buybackoff** [comment]
BTW, look into `compress.bat`. To build without changing it you should put native shared libs not into `lib/out` as I wrote above but in the folder `lib/libspreadsdb/src/libspreadsdb` - where Make would produce LMDS's artifacts.

**Comment by Nekromancer** [comment]
Yes, i noticed that :)
