### ISSUE TITLE
Allow config to be set when Bootstrapper is not available.

### ISSUE THREAD

**Issue by vinaychandra** [Spreads/Spreads.LMDB#34]
If for any reason, Bootstrapper class is not able to be initialized (see [this](https://github.com/Spreads/Spreads/issues/171)), Config can never be initialized. Please allow the `DefaultLocation` to be settable when the `Bootstrapper` class is unavailable.

**Comment by buybackoff** [comment]
Please see #33 and #28. Bootstrapper is no longer used and native binaries are packed with NuGet.

**Comment by buybackoff** [comment]
@vinaychandra NuGet is updated
