### ISSUE TITLE
Replace blocking concurrent queue with non-blocking channel?

### ISSUE THREAD

**Issue by wangjia184** [Spreads/Spreads.LMDB#36]
> Write transactions are executed in a single thread via a blocking concurrent queue. 

it is better to replace blocking queue with [Channel<T>](https://docs.microsoft.com/en-us/dotnet/api/system.threading.channels.channel-1?view=netcore-3.0).

The former blocks a thread when waiting for new data; The latter is totally non-blocking hence you can free up thread when there is no data to write.

**Comment by buybackoff** [comment]
I'm actually thinking about removing the writer thread completely. LMDB is single-write and enforces that. In .NET you could just use `Task.Run` if you do not want to block the current thread and fire-and-forget a transaction.

What is your use case where this is important?
