### ISSUE TITLE
How to direct use string as key and value?

### ISSUE THREAD

**Issue by RockNHawk** [Spreads/Spreads.LMDB#37]
I'm trying direct put string's pointer and get the stirng size to DirectBuffer, but I got and DirectBuffer size not fixed
or  MDB_KEYEXIST: Key/data pair already exists error.

    using (var tx = envS.BeginTransaction(TransactionBeginFlags.ReadWrite))
    {
        for (int i = 0; i < runCount; i++)
        {
            var keyAndValue = i.ToString();
            unsafe
            {
                fixed (char* p = keyAndValue)
                {
                    var size = keyAndValue.Length * sizeof(Char);
                    var key1 = new DirectBuffer((long) size, (byte*) p);
                    var value = new DirectBuffer((long) size, (byte*) p);
                    dbS.Put(tx, ref key1, ref value, TransactionPutOptions.AppendData);
                }
            }
        }
        tx.Commit();
    }

Could you tell me how to direct use string as key and value ?Thank you!

**Comment by buybackoff** [comment]
I guess you get MDB_KEYEXIST when i = 10, because it sorts before 2 and you use TransactionPutOptions.AppendData

**Comment by RockNHawk** [comment]
uh, yeah, you're amazing...

**Comment by RockNHawk** [comment]
After I change`TransactionPutOptions` to `NoDuplicateData`, it worked, Thank you!

I have another question, I define a custom strcut with StructLayout and BinrySerialization Size setted, I have tried many time but also get an 'Type StringAsStruct is not fixed size' error, could you tell me how to defina a custom sturct to work with LMDB?


    [BinarySerialization(40)]
    [StructLayout(LayoutKind.Sequential, Pack = 1,Size = 40)]
    unsafe struct StringAsStruct
    {
        public fixed char Data[20];
    }


    for (int i = 0; i < runCount; i++)
    {
        var keyAndValue = i.ToString();
        unsafe
        {
            fixed (char* p = keyAndValue)
            {
                var st = new StringAsStruct();
                *st.Data = p[0];
                var s = new string(st.Data);
            //   Console.WriteLine(s);
                // FileWorkItemState is a struct with an enum field works well with LMDB
                dbS.Put(tx, st, new FileWorkItemState(), TransactionPutOptions.NoDuplicateData);
            }
        }
    }

**Comment by RockNHawk** [comment]
I resolved it by myself, excuse me is it the best practice?


    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    struct StringAsStruct2
    {
        /*
         *
         * create fixed size string in a struct in C#?
         * https://stackoverflow.com/questions/19152441/create-fixed-size-string-in-a-struct-in-c
         *
         *
         * https://stackoverflow.com/questions/46279646/safe-fixed-size-array-in-struct-c-sharp
         * 
         */

        public byte Length;
        public char Data;
    }
    
    for (int i = 0; i < runCount; i++)
    {
        var keyAndValue = i.ToString();
        unsafe
        {
            fixed (char* p = keyAndValue)
            {
                var st = new StringAsStruct2();
                st.Length = (byte)keyAndValue.Length;
                st.Data = *p;
                dbS.Put(tx, st, new FileWorkItemState(), TransactionPutOptions.NoDuplicateData);
            }
        }
    }

**Comment by buybackoff** [comment]
It's normal to pin a string and use a char pointer. But you are working with UTF16 encoding, but probably you may want to use UTF8. In that case you could estimate byte count using [this](https://docs.microsoft.com/en-us/dotnet/api/system.text.utf8encoding.getbytecount?view=netframework-4.8), get a temp buffer from an array pool or use thread-static one, pin that buffer using `fixed`, get UTF8 bytes from string using [this](https://docs.microsoft.com/en-us/dotnet/api/system.text.utf8encoding.getbytes?view=netframework-4.8#System_Text_UTF8Encoding_GetBytes_System_Char__System_Int32_System_Byte__System_Int32_) and then use the byte buffer wrapped into DirectBuffer as a key. If UTF16 is not an issue than I do not see any issues.

**Comment by RockNHawk** [comment]
Thank you ! I'll make a performance test to determine direct use UTF16 or convert it to UTF8 .

Spreads.LMDB is faster than Leveldb.Standard （.NET Wrapped）, zero GC, so cool.
