### ISSUE TITLE
How to enumerate by a string prefix ?

### ISSUE THREAD

**Issue by RockNHawk** [Spreads/Spreads.LMDB#38]
Hello, I saw that lmdb can use key prefix for query, but I can't find related examples.

Could you tell me how can I use a prefix of string type for query? For example, use a `C:\data` as a key prefix to match `C:\data\sub1`, `C:\data\sub1\123`

Thank you!

**Comment by buybackoff** [comment]
You use SET_RANGE option (http://www.lmdb.tech/doc/group__mdb.html#gga1206b2af8b95e7f6b0ef6b28708c9127af9feb0557c2954dbf7732eee5e1b59e7) for a cursor to position to the first element greater than or equal to a key, and enumerate (MDB_NEXT) starting from that until the prefix is still valid.

You could also use Spreads-specific helpers methods `TryFind` with `Lookup` option https://github.com/Spreads/Spreads.LMDB/blob/d790026793942b03f12dabf09fa49eb7968f0239/src/Spreads.LMDB/Cursor.cs#L33-L55 to position the cursor e.g. to an element `GreaterThan/LessThan/GreaterOrEqual/LessOrEqual` your search key.

**Comment by RockNHawk** [comment]
Thank you very mutch ! It's OK!

just a samll issue, if I set `Lookup` to `Lookup.GE` in a `while` in `cursor` ,

	while (cursor.TryFind(Lookup.GE, ref keyPrefixBuffer, out var val))

it make a deat loop, if I change it to `Lookup.GT` it works well.

Paste my code for others' to refer:

	using System;
	using System.IO;
	using System.Linq;
	using System.Threading.Tasks;
	using NUnit.Framework;
	using Spreads;
	using Spreads.Buffers;
	using Spreads.LMDB;

	namespace Test
	{
		[TestFixture]
		public class LMDBTest
		{
			[TestCase]
			public async Task KeyPrefixQuery()
			{
				var path = "./temp/lmdb";
				if (Directory.Exists(path))
				{
					Directory.Delete(path, true);
				}

				var dirS = Path.Combine(path, "Spreads" + Guid.NewGuid());
				Directory.CreateDirectory(dirS);

				var envS = LMDBEnvironment.Create(dirS, LMDBEnvironmentFlags.NoSync | LMDBEnvironmentFlags.NoLock,
					disableAsync: true);
				envS.MaxDatabases = 10;
				envS.MapSize = 256 * 1024 * 1024;
				envS.Open();
				envS.TouchSpace(500);

				Console.WriteLine("USED SIZE: " + envS.UsedSize);

				var dbS = envS.OpenDatabase("SimpleWrite", new DatabaseConfig(DbFlags.Create));

				// {
				var baseString = @"C:\data\";


				var subNames = new string[] {"sub1", "sub2", "sub3"};
				var subFullNames = subNames.Select(x => $"{baseString}{x}").ToArray();

				using (var tx = envS.BeginTransaction(TransactionBeginFlags.ReadWrite))
				{
					unsafe void PutSubs(string s)
					{
						foreach (var keyAndValue in subFullNames)
						{
							// var keyAndValue = $"{s}{append}";
							unsafe
							{
								fixed (char* p = keyAndValue)
								{
									var size = keyAndValue.Length * sizeof(Char);
									var key1 = new DirectBuffer((long) size, (byte*) p);
									var value = new DirectBuffer((long) size, (byte*) p);
									dbS.Put(tx, ref key1, ref value, TransactionPutOptions.NoDuplicateData);
								}
							}
						}
					}

					PutSubs(baseString);
					PutSubs(@"C:\data-1\");
					PutSubs(@"C:\data-2\");

					tx.Commit();
				}


				using (var tx = envS.BeginTransaction(TransactionBeginFlags.ReadWrite))
				{
					using (var cursor = dbS.OpenReadOnlyCursor(tx))
					{
						var keyPrefix = baseString;
						unsafe
						{
							fixed (char* keyPrefixPt = keyPrefix)
							{
								var size = keyPrefix.Length * sizeof(Char);
								var keyPrefixBuffer = new DirectBuffer((long) size, (byte*) keyPrefixPt);
								//  dbS.TryFindDup(tx, Lookup.GT, ref key1,ref var) ;
								while (cursor.TryFind(Lookup.GT, ref keyPrefixBuffer, out var val))
								{
									char* aChar = (char*) val.IntPtr.ToPointer();
									var str = new string(aChar);
									// the last byte may not used by char
									if (str.Length > (val.Span.Length / 2))
									{
										str = new string(str.AsSpan(0, str.Length - 1));
									}

									//  var str = new string(new ReadOnlySpan<char>(val.IntPtr.ToPointer()));
									Assert.Contains(str, subFullNames);
									Console.WriteLine($"Find:{str}");
								}
							}
						}
					}
				}
				// });

				// Console.WriteLine(lmdbWriteCode.Start());
			}
		}
	}


out put:

> USED SIZE: 214769664
> Find:C:\data\sub1
> Find:C:\data\sub2
> Find:C:\data\sub3

**Comment by buybackoff** [comment]
> it make a dead loop, if I change it to Lookup.GT it works well.

GE is Greater *Or Equal*, if the key is equal the cursor stays on the same position.

You should never use TryFind in a loop, it's O(log N), basically binary search on B+-tree.

There are two types of moves for the cursor: absolute and relative. Absolute ones are MOVE_FIRST, MOVE_LAST, SET_RANGE, TryFind(Lookup). Relative ones are MOVE_NEXT, MOVE_PREV. The cursor has state (the current key where the cursor is positioned). After successful absolute move you should then move next/previous. With Lookup.GT you are performing binary search vs. current position and basically moving next, but in a very inefficient way - finding a key that is greater than the current one, not just moving next.

Also remember that after unsuccessful cursor move it's current position *is undefined*, you cannot rely on it's previous position. I've had several bugs when I assumed that LMDB's cursor current key remains the same after bad move.

**Comment by RockNHawk** [comment]
Ah, I see. Thank you for the detailed explanation ! ☕️☕️

I should use this API `public bool TryGet(ref DirectBuffer key, ref DirectBuffer value, CursorGetOption operation)`

First use `CursorGetOption.SetRang` to absolute  move to the first matched redord, then loop and use `CursorGetOption.Next`

**Comment by buybackoff** [comment]
Yes, and `TryGet(..., SetRange)` is the same as `TryFind(..., Lookup.GE)`. After you call `MoveNext` you first check if the key after the move is still in the range.

**Comment by RockNHawk** [comment]
Okay, thank you!
