### ISSUE TITLE
Unable to find package System.Runtime.Intrinsics.Experimental

### ISSUE THREAD

**Issue by Nekromancer** [Spreads/Spreads.LMDB#4]
I'm trying to use your library in my .net standard library. In main project (TargetFramework .net standard 2.0) everything is ok, but i cannot compile test project (TargetFramework netcoreapp2.1). Test project have main project as reference. Error below. Have you any idea how to resolve this?

Also - i cannot get nuget itself on test project. The same error occures

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1102	Unable to find package System.Runtime.Intrinsics.Experimental with version (>= 4.6.0-preview1-26724-02)
  - Found 2 version(s) in nuget.org [ Nearest version: 4.5.0-rc1 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages	
```

**Comment by buybackoff** [comment]
It is used now e.g. for CRC32 fast implementation using CPU intrinsics: https://github.com/Spreads/Spreads/commit/1a6b6c252989bf5071be23366a78429aa6751955

**Comment by Nekromancer** [comment]
Seems fair. I'm tight to .NET Framework for now, but nuget will work just fine
