### ISSUE TITLE
Win x86 support ?

### ISSUE THREAD

**Issue by RockNHawk** [Spreads/Spreads.LMDB#40]
Hi,

Spreads.LMDB work well on x64, but in Windows x86 , will throw a `libspreads_lmdb.dll` not found error.

I'v fond `libspreads_native.dll` in `x86` bin folder, but `libspreads_lmdb.dll` only in `x64` folder,

does preads.LMDB support Windows x86?

Thank you!

**Comment by buybackoff** [comment]
LMDB does support x86, but the file formats are not binary compatible with x64, so for me it was a deal breaker. Also it's much slower. So I didn't compile for x86.

But you could compile it yourself or get the binary somewhere else and place next to dll, it should just work.

**Comment by buybackoff** [comment]
https://www.nuget.org/packages/LightningDB/ has it. You will need to rename it though and Spreads' helper methods won't work (e.g. Find LessOrEqual and similar)

**Comment by RockNHawk** [comment]
Thanks for your guidance, I have some compile environment error, could you help me, I installed MinGW, and installed these package:

![image](https://user-images.githubusercontent.com/3222379/79726029-bcea0e00-831c-11ea-9ffc-bd560c4ad398.png)

but when i run `mingw32-make.exe` in  `Spreads.LMDB\lib\libspreadsdb\src\libspreadsdb` folder, this error happened: 

    error: unknown type name 'NtCreateSectionFunc'

Thank you!

**Comment by buybackoff** [comment]
Something with `#ifdef`s. Those symbols are defined by LMDB for not to include them from windows headers. The place where they are defined is unreachable.

**Comment by RockNHawk** [comment]
I giveuped ...., thank you.

**Comment by buybackoff** [comment]
Why could't you just use the existing binary?

**Comment by RockNHawk** [comment]
I used the existing binary from LightingDB, but have exception, I will take a debug for more detail info, here is the simple exception info:

    Error Open DB Environment C:\Users\Administrator\Data\Volume.C:MDB_INVALID: File is not an LMDB file
    Spreads.LMDB.LMDBException: MDB_INVALID: File is not an LMDB file
    at Spreads.LMDB.Interop.NativeMethods.ThrowLMDBEx(Int32 res) in G:\Dev\FIDS\lib\DataSpreads\lib\Spreads.LMDB\src\Spreads.LMDB\Interop\NativeMethods.cs:line 127
    at Spreads.LMDB.LMDBEnvironment.Open() in G:\Dev\FIDS\lib\DataSpreads\lib\Spreads.LMDB\src\Spreads.LMDB\LMDBEnvironment.cs:line 193
    

this exception's exception.Message is `Exception of type 'Spreads.LMDB.LMDBException' was thrown.`

    Spreads.LMDB.LMDBException: Exception of type 'Spreads.LMDB.LMDBException' was thrown.
    at Spreads.LMDB.Interop.NativeMethods.ThrowLMDBEx(Int32 res) in G:\Dev\FIDS\lib\DataSpreads\lib\Spreads.LMDB\src\Spreads.LMDB\Interop\NativeMethods.cs:line 127
    at Spreads.LMDB.LMDBEnvironment.Open() in G:\Dev\FIDS\lib\DataSpreads\lib\Spreads.LMDB\src\Spreads.LMDB\LMDBEnvironment.cs:line 193
    at Labx.LMDB.LmDatabase`2.InitAsync(ITrace parentTrace) in C:\git\app\src\Labx.LMDB\LmDatabase.cs:line 163

**Comment by buybackoff** [comment]
Are you trying to open a file created by x64?

**Comment by RockNHawk** [comment]
@buybackoff No, db file is new created.
The first case is re-open a db file created by x86 version, and the db file have data.

**Comment by buybackoff** [comment]
> May be the https://www.nuget.org/packages/LightningDB/ LMDB version mismatch？

It's the same thing, different names.

> Could you compile a spreads lmdb dll for me?

No, not until I need it myself. Look at Makefile (upstream and Spreads), it's very simple for x64. For x86 you may need to define some params (commnented in Makefile), download MinGW x86 (or try to use https://github.com/microsoft/vcpkg, but I do not know if it supports x86), and if you are lucky you will get the binary in 20 mins total. Or you will have to dig deeper and investigate, then test that it really works.

> Because I used some spleads extended feature like Find.

You may look how the Find methods are implemented here: https://github.com/Spreads/Spreads.LMDB/blob/master/lib/libspreadsdb/src/libspreadsdb/spreadsdb.c Nothing stops you from doing the same in C#.

**Comment by buybackoff** [comment]
Win x86 is not supported by this project. (same as nested transactions)

A pool request with x86-adjusted Makefile and instructions to build is welcome.

**Comment by RockNHawk** [comment]
Okay, thank you very much !!
