### ISSUE TITLE
Should it be possible to enumerate just keys (and not values) with a cursor?

### ISSUE THREAD

**Issue by BernMcCarty** [Spreads/Spreads.LMDB#42]
Does the native LMDB API allow for passing NULL as the data parameter to mdb_cursor_get() and thus allow you to enumerate just keys?  If so, does Spreads.LMDB expose this ability somehow?

What is the most performant way to check if a database has an entry for a specific key when that is all that you want to know and you do not want the value?

**Comment by buybackoff** [comment]
`MDB_SET`/`CursorGetOption.SetKey` should work like this
http://www.lmdb.tech/doc/group__mdb.html#ga1206b2af8b95e7f6b0ef6b28708c9127

This is actually one of the gotchas: position of a cursor in undefined after any unsuccessful move so `SetKey` is often needed to reposition the cursor to where it was.
