### ISSUE TITLE
Issue with multiple data write

### ISSUE THREAD

**Issue by Nekromancer** [Spreads/Spreads.LMDB#8]
Hi,

Could you help me out with and issue i'm having.. For the purpose of SoundFingerprinting algorithm i'm trying to use multiple data as `Dictionary<int, Set<ulong>>()` and (i far as i understandard LMDB) that it should work this way. But i found an use case when written values are just.. wrong. And i can't find out why is that happening. If you could take a look at this code (it's full issue reproduction in xunit test)
[SpreadsLMDBBugRepro.zip](https://github.com/Spreads/Spreads.LMDB/files/2378375/SpreadsLMDBBugRepro.zip)

**Comment by buybackoff** [comment]
Line 126: `if (cursor.TryGet(ref key, ref value, CursorGetOption.***Set***)`. 

`CursorGetOption.First`: 

> Position at first key/data item

`CursorGetOption.Set`:

> Position at specified key

`CursorGetOption.FirstDuplicate`:

> Position at first data item of current key. Only for MDB_DUPSORT

Looks like `First` is absolute, you need to `Set` to your key.

**Comment by Nekromancer** [comment]
Thanks! Frankly i wouldn't find out that myself. Cursors in LMDB are really confusing

**Comment by buybackoff** [comment]
You need to read the docs as a legal document and make no assumptions. It actually behaves exactly like documented. But some explanation redundancy in cursors behavior would be nice, have to learn by trial & error often.
